### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by limelect** [tinyBigGAMES/GameVision#5]
D10.2.3
On GameVision.Console; i added
function GetConsoleWindow: hWnd; stdcall;  external kernel32 name 'GetConsoleWindow';
On GameVision.CmdLine;
[dcc64 Error] GameVision.CmdLine.pas(210): E2010 Incompatible types: 'TStringDynArray' and 'System.TArray<System.string>'
and may be more

**Comment by jarroddavis6889** [comment]
Ahh, apparently GetconsoleWindow is not defined in WinApi.Windows for D10.2.3, ok, I added the definition, thanks.

Can you please try this for the 2nd issue:
- Add TStringDynArray = System.TArray<System.string>; to GameVision.Common
- In GameVision.CmdLine, add GameVision.Common to uses in the implementation section.
- Let me know if this works for you and I will then update the sources.

Thanks for reporting!

**Comment by limelect** [comment]
TStringDynArray = System.TArray<System.string>; to GameVision.Common this is OK

But then too many more errors.
I give up
Test for D10.2

**Comment by jarroddavis6889** [comment]
If you are getting more errors related to TStringDynArray, there are a few more places where this needs to be changed also. System.Types has TStringDynArray defined in 11/11.1. If this is the case I've already changed it throughout the codebase and you can just grab the repo once I push it up. If there are other issues, then they would need to be addressed, so if you could give me an idea of what they might be I can see what I do to fix. One thing, Database/Highscore uses FireDAC if you have community edition, this may not compile.

**Comment by limelect** [comment]
All kind of errors

**Comment by limelect** [comment]
Checking project dependencies...
Compiling GVExamples.dproj (Distro, Win64)
dcc64 command line for "GVExamples.dpr"
  c:\program files (x86)\embarcadero\studio\19.0\bin\dcc64.exe -$D0 -$L- -$Y- --no-config -M -Q -TX.exe 
  -AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;
  DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DRELEASE -E..\bin -I..\sources;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -LEC:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64 
  -LNC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64 -NU.\Win64\Distro -NSWinapi;System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;
  System;Xml;Data;Datasnap;Web;Soap; -O..\sources;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -R..\sources;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -U..\sources;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -CC -NBC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64 
  -NHC:\Users\Public\Documents\Embarcadero\Studio\19.0\hpp\Win64 -NO.\Win64\Distro   GVExamples.dpr   
[dcc64 Error] GameVision.Lua.pas(166): E2003 Undeclared identifier: 'TNoRefCountObject'
[dcc64 Error] GameVision.Lua.pas(166): E2021 Class type required
[dcc64 Error] GameVision.Lua.pas(196): E2005 'TNoRefCountObject' is not a type identifier
[dcc64 Error] GameVision.Lua.pas(196): E2021 Class type required
[dcc64 Error] GameVision.Lua.pas(153): E2291 Missing implementation of interface method IInterface.QueryInterface
[dcc64 Error] GameVision.Lua.pas(153): E2291 Missing implementation of interface method IInterface._AddRef
[dcc64 Error] GameVision.Lua.pas(153): E2291 Missing implementation of interface method IInterface._Release
[dcc64 Error] GameVision.Lua.pas(154): E2291 Missing implementation of interface method IInterface.QueryInterface
[dcc64 Error] GameVision.Lua.pas(154): E2291 Missing implementation of interface method IInterface._AddRef
[dcc64 Error] GameVision.Lua.pas(154): E2291 Missing implementation of interface method IInterface._Release
[dcc64 Fatal Error] GameVision.Lua.pas(357): F2063 Could not compile used unit 'GameVision.LuaJIT.pas'
Failed
Elapsed time: 00:00:00.5

**Comment by limelect** [comment]
Checking project dependencies...
Compiling GVExamples.dproj (Distro, Win64)
dcc64 command line for "GVExamples.dpr"
  c:\program files (x86)\embarcadero\studio\19.0\bin\dcc64.exe -$D0 -$L- -$Y- --no-config -M -Q -TX.exe 
  -AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;
  DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DRELEASE -E..\bin -I..\sources;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -LEC:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64 
  -LNC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64 -NU.\Win64\Distro -NSWinapi;System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;
  System;Xml;Data;Datasnap;Web;Soap; -O..\sources;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -R..\sources;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -U..\sources;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -CC -NBC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64 
  -NHC:\Users\Public\Documents\Embarcadero\Studio\19.0\hpp\Win64 -NO.\Win64\Distro   GVExamples.dpr   
[dcc64 Error] GameVision.Async.pas(164): E2197 Constant object cannot be passed as var parameter
[dcc64 Fatal Error] GameVision.Core.pas(156): F2063 Could not compile used unit 'GameVision.Async.pas'
Failed
Elapsed time: 00:00:00.2

I put some error

**Comment by jarroddavis6889** [comment]
1. Add System.Generics.Defaults to the uses section
2. Change TNoRefCountObject to TSingletonImplementation
3. Add LAsyncThread2: TGVAsyncThread; to var section of procedure TGVAsync.Process;
4. Add LAsyncThread2 := LAsyncThread; before FreeAndNil(LAsyncThread);
5. Change FreeAndNil(LAsyncThread) to FreeAndNil(LAsyncThread2)

**Comment by limelect** [comment]
can you update the source?

**Comment by jarroddavis6889** [comment]
Done

**Comment by limelect** [comment]
D10.2.3
FireDAC.Phys.SQLiteWrapper missing
I am having fun

**Comment by limelect** [comment]
I deleated the above  just to see whatr will happen and
Checking project dependencies...
Compiling GVExamples.dproj (Debug, Win64)
dcc64 command line for "GVExamples.dpr"
  c:\program files (x86)\embarcadero\studio\19.0\bin\dcc64.exe -$O- -$W+ -$R+ -$Q+ --no-config -M -Q -TX.exe 
  -AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;
  DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DDEBUG -E..\bin -I"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\debug";..\sources;"c:\program 
  files (x86)\embarcadero\studio\19.0\lib\Win64\release";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\19.0\include";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program 
  Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -LEC:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64 
  -LNC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64 -NU.\Win64\Debug -NSWinapi;System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;
  System;Xml;Data;Datasnap;Web;Soap; -O..\sources;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -R..\sources;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -U"c:\program files (x86)\embarcadero\studio\19.0\lib\Win64\debug";..\sources;"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win64\release";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64;"c:\program files 
  (x86)\embarcadero\studio\19.0\include";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program 
  Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win64";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win64";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD 
  Studio 10.2 Tokyo\Win64\Release" -CC -V -VN -VR -NBC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp\Win64 
  -NHC:\Users\Public\Documents\Embarcadero\Studio\19.0\hpp\Win64 -NO.\Win64\Debug   GVExamples.dpr   
[dcc64 Error] GameVision.Deps.pas(163): E2010 Incompatible types: 'string' and 'TResourceStream'
[dcc64 Error] GameVision.Deps.pas(177): E2010 Incompatible types: 'System.TArray<System.string>' and 'TStringDynArray'
[dcc64 Fatal Error] GameVision.Database.pas(209): F2063 Could not compile used unit 'GameVision.Deps.pas'
Failed
Elapsed time: 00:00:00.9

**Comment by limelect** [comment]
Plz do NOT put any unchecked source. It makes you look bad and unproffesiona

**Comment by jarroddavis6889** [comment]
Well, first of all, it has been stated that GV is compatible with the latest release of the community addition version and that database uses FireDAC so an edition of that version which supports remote connection is needed. Out of courtesy to you, I've been trying to help you get it compiled with a version that I do not officially support.

**Comment by limelect** [comment]
No problem thanks. If it is not compatible with 10.2 or 10.3 only 10.4 and above plz state so.
Furthermore D7 and up are still active.
If you want only small !! section of the Delphi community to use your software so be it
No problem.
So plz state so in your readme
So thanks again. and good luck

**Comment by jarroddavis6889** [comment]
readme.md
Minimum System Requirements
- [Delphi Community Edition](https://www.embarcadero.com/products/delphi/starter)
- Microsoft Windows 10, 64 bits
- OpenGL 3

The Delphi community edition is ALWAYS the last generation version, so yes, I did state this fact.

I WAS trying to help get it working for your version, but you proceeded to tell me that I'm not being professional????

**Comment by limelect** [comment]
I'm not being professional????
Sorry I did not mean to be prudent 
Only that you need to know that working with the latest Delphi you loose
a big chunk of the Delphi users.
I work with D10.2.3 always a paid version. where I started with D1 !!!!
I respect your decision so good luck. I will not buy a new Delphi just for that

**Comment by jarroddavis6889** [comment]
Bro, not once have I asked you to upgrade to a recent version of Delphi just to use my software. I would never even try to do such a thing. I understand that everyone is not going to have the latest version, so therefore I was attempting to work you with to sort out the issues so that we could get it working with your version, then we would know that at least this version and higher is now covered. But rather than continuing to work with me you got angry and started to tell me what you were not going to do and that I'm not being professional etc. I was simply trying, with your assistance, to get it working. If you would have just continued to tell me what errors you are getting, I could have gotten them all sorted out.

I told you what changes to make on your end to see if I would compile, then we moved to the next until it we got it sorted out, THEN I could commit to the repo and everyone could thus benefit. Your response to me, I'm not going to d/l anymore until it works with my version of Delphi and checking in unchecked code makes you look unprofessional, blah blah. 

I cannot install every single version of Delphi. It's a maintenance nightmare. Props to those developers that have managed to do so. My initial goal was to at least be compatible with the community edition up and anyone who reports issue we work together to get them sorted out as best as I can. So really, it was use that took that stance, I have been trying to help all the time.

**Comment by limelect** [comment]
Sorry I did not mean to get you angry.
I am professional software eng for over 40 years.
I use a professional Delphi-paid one. 
But never have time to debug others' software altho I would like
to help but have my own project.
See www.limelect.com for where you will find my free goodies
https://limelect.com/free-programs/
So plz sorry and good luck

**Comment by jarroddavis6889** [comment]
I'm not angry, I was just trying to help. Respect.

I'm working on a new project that should be able to work on all Unicode/win64 versions of Delphi. Here is a link to a test I put together: https://tinybiggames.com/temp/Test01.zip. You should (crossing fingers, hehe), be able to compile and run. You should see some primitives displayed on screen. Let me know.

**Comment by limelect** [comment]
![Screenshot - 09_06_2022 , 13_48_39](https://user-images.githubusercontent.com/4199131/172830028-08ce9f1c-0eb1-4b64-8872-46233f30aa05.jpg)
 It speek for itself

**Comment by jarroddavis6889** [comment]
What version of windows are you using?

**Comment by limelect** [comment]
7
